use_frameworks!
source 'https://github.com/BeyChan/CMYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'CMYRefresh_Example' do
  pod 'CMYRefresh', :path => '../'

  target 'CMYRefresh_Tests' do
    inherit! :search_paths

    
  end
end
